version: '3.7'
services:
  sobre_abondance_front:
    #image: yassinsiouda/sobre-abondance-front:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3005:3000
    stdin_open: true